### ISSUE TITLE
myAttributeError: module 'cv2.cv2' has no attribute 'drawKeypoints'

### ISSUE THREAD

**Issue by OIdiotLin** [rwightman/posenet-pytorch#1]
## Enviornment

- OS: Linux x64
- Python: 3.7.2
- OpenCV: 4.0.0.21

## Reproduction

Just run `python image_demo.py` and an error is thrown.

![opencv-drawkp](https://user-images.githubusercontent.com/8947243/52172551-c5543880-27ac-11e9-999a-8414622fc5f5.png)

**Comment by OIdiotLin** [comment]
Well, I just find the reason here [skvark/opencv-python#168](https://github.com/skvark/opencv-python/issues/168).

It seems that **the function missing could be repaired in OpenCV 4.0.1.**

For me, I reinstall **version 3.4.5.20** instead. :rofl:

**Comment by rwightman** [comment]
yeah, kind of annoying they released 4.x with that bug. I'll improve the note in the README about it...
