### ISSUE TITLE
Single pose decoding

### ISSUE THREAD

**Issue by JunkyByte** [rwightman/posenet-pytorch#3]
Hey there, do you have any example of the usage of the single pose decoding?
I've been messing with the code a bit and I only see multiple poses in the examples, would love to be able to use single pose instead (also to verify the accuracy tradeoff between the two)

Thank you!

**Comment by rwightman** [comment]
I didn't port the single pose decoding and don't intend to. Using the template of multi-pose code written and the reference JavaScript impl, wouldn't be too hard to implement the single pose version.
