### ISSUE TITLE
About net

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [rwightman/posenet-pytorch#4]
@rwightman Thank you for your nice job.
1.Which paper corresponding to PoseNet?I google a lot but...sad
2.What is offset and displacements?Just like define in https://arxiv.org/abs/1803.08225 ?

**Comment by rwightman** [comment]
@MoonBunnyZZZ yes, that's the paper associated with this... this impl by google was optimized for inference speed though, so they removed some of what is described in the paper. Only one offset is used here but both a short and mid-range offset are described in the paper. If you look at the original TF network graph more closely, there is another set of offsets, but it's not used.
