### ISSUE TITLE
About how to change model

### ISSUE THREAD

**Issue by MarkKang05** [rwightman/posenet-pytorch#7]
Hi!  rwightman!
you're project is perfect.Its activated successfully on my laptop.
but my laptop is too slow.
so i try to change other model(more light, and more fast). I saw in your post that the weight is google's model is original. And i entered link (that you're linked,  this -->>  https://github.com/tensorflow/tfjs-models/tree/master/posenet )
but i couldnt found model.. and its just js code. I dont know how to convert to python code.
thank you..

**Comment by ggzzzzz628** [comment]
I also encountered this problem, I want to transfer the issue of resnet50 to python. Can you solve this problem?
@MarkKang05

**Comment by rwightman** [comment]
@MarkKang05 there is support for the different model multipliers of the mobilenet weights from the original tfjs release in the included scripts, just use a different  `--model`  argument

Available models via the argument (use the integer in the argument) include:
```
MOBILENET_V1_CHECKPOINTS = {
    50: 'mobilenet_v1_050',
    75: 'mobilenet_v1_075',
    100: 'mobilenet_v1_100',
    101: 'mobilenet_v1_101'
}
```

**Comment by ggzzzzz628** [comment]
I am watching people on the Internet saying that there is a version of resnet. How do I get the pre-training model of the resnet version? @rwightman

**Comment by rwightman** [comment]
@gzchenjiajun there is already an issue for that, #2 ... I have not ported the ResNet50 weights, the model format was changed so it requires more work and I haven't had the time
