### ISSUE TITLE
How to train new model

### ISSUE THREAD

**Issue by amitabhama** [rwightman/posenet-pytorch#8]

**Comment by amitabhama** [comment]
HI, author, thanks for your code, it is perfect! But i want to know How to train this model, as a your code starer, i really want the train code. Thank you for your reading

**Comment by rwightman** [comment]
@amitabhama  You'd have to ask Google, the training of these models was based on the PersonLab paper. Please see: https://github.com/tensorflow/tfjs/issues/1581

Building the training setup from scratch is certainly doable but it's a significant undertaking. I'm open to doing it on a contract basis but it's beyond the scope of something I plan to add here.

**Comment by amitabhama** [comment]
@rwightman ok, thank you for your answer, i'm trying to do the train code. Blessing you, mogul

**Comment by rwightman** [comment]
@amitabhama have fun, let me know if you get it working, I'm sure others will be interested too

**Comment by edwardnguyen1705** [comment]
Hi @amitabhama ,
Have you got the training code worked?
